### ISSUE TITLE
[feature] config option for string formatting

### ISSUE THREAD

**Issue by JakeStanger** [JakeStanger/mpd-discord-rpc#1]
Add a configuration option to change the string display format for both the details (song title) and state (artist / album) to allow for custom formatting.

For example the current default config options might look like:

```toml
[format]
details = "$title"
state = "$artist / $album"
```

---

@Phate6660 I spotted your fork, thank you for the inspiration for this and the kind words. I'm glad you like it :)
