### ISSUE TITLE
[new-feature-request] Adding rich presence buttons 

### ISSUE THREAD

**Issue by DestroyerAce** [JakeStanger/mpd-discord-rpc#32]
It would be nice if there's a button that shows link for what song you are playing on spotify or/and youtube

**Comment by JakeStanger** [comment]
Happy to add this. MusicBrainz has info for Spotify/YouTube links so I can pull it from there. If it doesn't exist there though for a particular song, I think I'll have to fall back to not displaying them for now. The alternative would be to search and hope the result comes back correct, which would also require users to add API keys to their config.

**Comment by JakeStanger** [comment]
So I've had a look into this, and there are two big issues I see:

- None of the Discord RPC libraries have button support currently. It can be patched in, but it seems to work in a bit of a weird way so it's a bit of work.
- More importantly, very few tracks in the MusicBrainz database have streaming links.

My concern is that it'd be quite a bit of work to add a feature that would be visible a fraction of the time. 

The immediate alternative method I see is to directly search YouTube/Spotify using their APIs, but as stated that would require users to obtain their own API keys and add them to the config, which I'm reluctant to add as a requirement and I suspect most people won't bother with. It also adds quite a lot more complexity to the program in general.

If yourself or anybody else has any other ideas, I'm happy to look into them and see if we can add it that way, but I'm going to have to halt this otherwise.

**Comment by natto1784** [comment]
There is one such library but it does not have the best code unfortunately. I have added a button as an example in my fork [here](https://github.com/natto1784/mpd-discord-rpc/tree/discord-rich-presence). If you decide to use it, I would also recommend using the [musicbrainz_rs](https://docs.rs/musicbrainz_rs/latest/musicbrainz_rs/) crate.

**Comment by JakeStanger** [comment]
Looks like I must have missed that library when I was looking. This solves problem 1 nicely, so we're one step closer.

The reason I'm not using a MusicBrainz library currently is that I can't see much advantage. I only need to perform a handful of basic HTTP requests at the moment and it doesn't feel like enough to warrant another dependency. If the scope of MusicBrainz integration ever expands, I'll definitely migrate over.

**Comment by 42willow** [comment]
Another use case for this would be to have a link to your music account profile (e.g. lastfm) which could be configurable and reduces complexity.

**Comment by ngoomie** [comment]
> Another use case for this would be to have a link to your music account profile (e.g. lastfm) which could be configurable and reduces complexity.

This is what I just came here to request, I'd quite like to have a link to my selfhosted scrobbler

**Comment by ReallyWeirdCat** [comment]
> > Another use case for this would be to have a link to your music account profile (e.g. lastfm) which could be configurable and reduces complexity.
> 
> This is what I just came here to request, I'd quite like to have a link to my selfhosted scrobbler

You can now do this with config parameters `button1_text`, `button1_link`, `button2_text`, `button2_link`, for static links it should be enough. Though it's also possible to use the dynamic parameters, this is what I do:

```toml
[format]
button1_text = "Search on YouTube"
button1_link = "https://www.youtube.com/results?search_query=$artist - $title"
```

**Comment by fxzzi** [comment]
just me or are the buttons borken? i just saw these got added, and I tried to add them to my config below:

```toml
hosts = ["localhost:6600"]

[format]
button1_link = "https://www.youtube.com/results?search_query=$artist - $title"
button1_text = "Listen on YouTube"
details = "$title"
display_type = "state"
large_image = "notes"
large_text = "$album"
small_image = ""
small_text = ""
state = "$artist"
timestamp = "both"
```

and uhh, i'm getting this:

```
ERROR mpd_discord_rpc: ErrorEvent { code: Some(4000), message: Some("child \"activity\" fails because [child \"buttons\" fails because [\"buttons\" at position 0 fails because [child \"url\" fails because [\"url\" must be a valid uri]]]]") }
```
